# # def makeAlbum(singer_Name1):
# #     album = {}
# #     album.update(album_Name1 = singer_Name1)
# #     # album["album_Name"] = album_Name1
# #     # album["singer_Name"] = singer_Name2
# #     # album["album_Name"] = album_Name2
# #     print(album)


# # if __name__ == "__main__":
# #     makeAlbum("tina")

# result ={
# 	"code": 0,
# 	"msg": "success",
# 	"data": {
# 		"page": {
# 			"total_counts": 1,
# 			"total_pages": 1,
# 			"current_page": 1,
# 			"size": 10
# 		},
# 		"site_y": ["00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30"],
# 		"site_x": [{
# 			"site_id": 957382335791171,
# 			"site_name": "周志泽场地"
# 		}],
# 		"list": [{
# 			"site_id": 957382335791171,
# 			"site_name": "周志泽场地",
# 			"site_data": [{
# 				"status": 1,
# 				"start_time": "00:00",
# 				"end_time": "00:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "00:30",
# 				"end_time": "01:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "01:00",
# 				"end_time": "01:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "01:30",
# 				"end_time": "02:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "02:00",
# 				"end_time": "02:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "02:30",
# 				"end_time": "03:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "03:00",
# 				"end_time": "03:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "03:30",
# 				"end_time": "04:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "04:00",
# 				"end_time": "04:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "04:30",
# 				"end_time": "05:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "05:00",
# 				"end_time": "05:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "05:30",
# 				"end_time": "06:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "06:00",
# 				"end_time": "06:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "06:30",
# 				"end_time": "07:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "07:00",
# 				"end_time": "07:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "07:30",
# 				"end_time": "08:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "08:00",
# 				"end_time": "08:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "08:30",
# 				"end_time": "09:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "09:00",
# 				"end_time": "09:30",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 1,
# 				"start_time": "09:30",
# 				"end_time": "10:00",
# 				"price": "0.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "10:00",
# 				"end_time": "10:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "10:30",
# 				"end_time": "11:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "11:00",
# 				"end_time": "11:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "11:30",
# 				"end_time": "12:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "12:00",
# 				"end_time": "12:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "12:30",
# 				"end_time": "13:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "13:00",
# 				"end_time": "13:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "13:30",
# 				"end_time": "14:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "14:00",
# 				"end_time": "14:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "14:30",
# 				"end_time": "15:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "15:00",
# 				"end_time": "15:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "15:30",
# 				"end_time": "16:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "16:00",
# 				"end_time": "16:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "16:30",
# 				"end_time": "17:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "17:00",
# 				"end_time": "17:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "17:30",
# 				"end_time": "18:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "18:00",
# 				"end_time": "18:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "18:30",
# 				"end_time": "19:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "19:00",
# 				"end_time": "19:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "19:30",
# 				"end_time": "20:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "20:00",
# 				"end_time": "20:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "20:30",
# 				"end_time": "21:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "21:00",
# 				"end_time": "21:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "21:30",
# 				"end_time": "22:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "22:00",
# 				"end_time": "22:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "22:30",
# 				"end_time": "23:00",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}, {
# 				"status": 2,
# 				"start_time": "23:00",
# 				"end_time": "23:30",
# 				"price": "1.0",
# 				"member_name": "",
# 				"mobile": ""
# 			}]
# 		}]
# 	}
# }
"""
venues_time = result["data"]["list"][0]["site_data"]
print([i for i in venues_time if i["status"]==2][0])
print(result["data"]["site_x"])
"""

import json

dict1 = {
    'name': 'tina',
    'age': 18,
    'nickname': 'GreenFlower',
}
t1 = (json.dumps(dict1))
print(type(t1))
t2 = json.loads(t1)
print(type(t2))
